export set LD_LIBRARY_PATH=/usr/local/lib
#export set SDL_VIDEODRIVER=wayland
#export set SDL_VIDEODRIVER=x11
#export set GDK_BACKEND=wayland
#export set QT_QPA_PLATFORM=wayland-egl

GOPATH=$HOME/sfw/go
export GOPATH

PATH=$PATH:~/.bin
PATH=$PATH:~/.cabal/bin
PATH=$PATH:~/.gem/ruby/2.2.0/bin
PATH=$PATH:~/go/bin
PATH=$PATH:/opt/gcw0-toolchain/usr/bin
PATH=$PATH:/opt/braid
PATH=$PATH:$LD_LIBRARY_PATH

CMAKE_ROOT=/usr/share/cmake-3.3
export CMAKE_ROOT

alias irssi="TERM=screen-256color irssi"
alias dmenu_run="LANG=en_US.UTF-8 dmenu_run"
alias dmenu="LANG=en_US.UTF-8 dmenu"
alias rustc-gcw0="rustc --target=mipsel-unknown-linux-gnu -C linker=mipsel-unknown-linux-gnu-cc"

#[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec weston
[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx

source ~/.bin/killproc.sh
source ~/.bin/d.sh
